### ISSUE TITLE
.Zarr Image Export Broken

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#19]
**Describe the bug**
When attempting to convert images into .zarr format, macos (both arm and x64 versions of pyreconstruct) fails to process images into the .zarr format. When prompt opens to show conversion activity, the process simply states that it needs to be provided arguements, then reports that it has been completed. The same process works correctly on windows 10/11.

**To Reproduce**
1. Go to Series > Images > convert to zarr
2. See error: 
Please provide arguments
Zarr processing finished.
You can close this window.

**Expected behavior**
.zarr folder created at the location chosen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS, both arm-64 and osx-64
 - Version 14.3.1

**Python (please indicate the version of Python you are using):**
- Version = 3.10 & 3.12, with all dependancies installed as well.

**Additional context**

**Comment by quasiTriestino** [comment]
Thanks for the note! So I'm sure I understand: Everything seems to be working ok on your Windows setup but failing in macOS 14.3.1? And you're working from the main branch at the most recent commit? 

Also: For the time being, PyReconstruct will likely fail at some point when run in Python 3.12. Best to install into a virtual environment running 3.11. (Some of its dependencies don't support 3.12.)

We'd like to make sure the zarr converter is working on all platforms, since you get a significant boost in speed when working with larger images. This is a huge improvement over legacy reconstruct.

Would you also please copy and paste the error message you get in the console here?

**Comment by AndrewLyon** [comment]
Surprisingly enough, I don't get an error from PyReconstruct itself, but I do get a metadata error from tifffile (this is consistent with both my macOS and windows installations).

My original setup on macOS was with python=3.10, but the issue continues after reinstalling in a new environment with 3.11 installed.

Attached is what I see:
![image_2024-02-23_120316068](https://github.com/SynapseWeb/PyReconstruct/assets/143132070/95b36861-a78e-4a5c-b972-1d9860f94fce)

**Comment by k34harris** [comment]
Hi Andrew,
Michael is on vacation for a couple weeks, so the response might be delayed.
Thanks for your ongoing interest and efforts!
*Kristen*
*Kristen M. Harris, PhD *
*Prof, Dept. of Neuroscience*
*Univ. of Texas at Austin*
*k ***@***.***>***@***.*** ***@***.***>,
**synapseweb.clm.utexas.edu
<http://synapseweb.clm.utexas.edu/>, *3DEM.org
*Pronouns:  She, Her, Hers*

**Comment by quasiTriestino** [comment]
@AndrewLyon Commit 6a4ec19d8fe07f972e1437e3669c84469db94422 (pushed to the main branch) introduces very minor changes to the main method of the zarr converter module. When you have a second, would you please give the converter a try through the GUI on your machine and let us know how it goes? Thanks!

**Comment by AndrewLyon** [comment]
Hi there, the .zarr conversion is still not working. This issue still applies to both my regular pyreconstruct environment (python 3.10) and my test environment (python 3.11).

I do want to note that the images are located on an external drive (if that matters), though terminal does have the appropriate access to all file locations on my system.

**Comment by quasiTriestino** [comment]
And you're still getting a message asking you to "Please provide arguments" in the zarr converter window?

**Comment by AndrewLyon** [comment]
Unfortunately, I've been using a windows vm to convert images to .zarr. Thank you!

**Comment by quasiTriestino** [comment]
@AndrewLyon We have created a new branch to try to suss out this issue. The branch is `fix/zarr-args`. When you have a second, would you please check out the branch and try to convert a series to zarr in your mac setup? If it works, great -- if not, would you please paste a screen shot of the messages you get in the converter window?

**Comment by AndrewLyon** [comment]
With the branch, this is what I get:
<img width="1728" alt="test_pyrecon" src="https://github.com/SynapseWeb/PyReconstruct/assets/143132070/7d1f59f3-abcc-45f0-aa59-9a7edd2f708a">

**Comment by julian-falco** [comment]
@AndrewLyon From the arguments shown, it appears that one of your folders intended to contain the zarr file contains a space (12_15_2023 Backup_EMMAdata copy ). The shell interprets it as completely separate arguments rather than as a single filepath. I will see if this can be screened for in the code, but in the meantime, could you rename the folder(s) so that there are no spaces in the filepath and try again?

**Comment by AndrewLyon** [comment]
removing the space works, thanks a ton!
