### ISSUE TITLE
3D scene/Vedo support for Wayland

### ISSUE THREAD

**Issue by dustenhubbard** [SynapseWeb/PyReconstruct#33]
### Describe the bug

PyReconstruct is cross platform and includes support for Linux. However, the 3D scene / Vedo module crashes PyReconstruct when utilizing the Wayland window display protocol. This is becoming the standard over X11 and is now shipping default in most modern Linux distributions and desktop environments.

### Commit or version

c383b95

### To Reproduce

1. Add object from Object List to 3D scene.
2. 3D scene window kills PyReconstruct running process completely.

### Expected behavior

I can drop back to the login display manager to select an X11 session to return to normal functioning 3D scene window. So far, all other PyReconstruct features function normally under Wayland.

### Desktop environment:

Arch Linux (kernel 6.10), DE: KDE 6.1.4

### Python version

python=3.11

**Comment by quasiTriestino** [comment]
Thanks for the note -- do you have Xwayland installed on your system?

**Comment by dustenhubbard** [comment]
Yep (xorg-xwayland 24.1.2-1)

**Comment by quasiTriestino** [comment]
The problem is likely that the main window is launched in Wayland and the 3D scene is instead being launched in X. To get around this, you can set the `QT_QPA_PLATFORM` environment variable to `xcb`. Running the following in a terminal:

`QT_QPA_PLATFORM=xcb <command to open PyReconstruct>`

should solve your problem. Thanks for the heads up!

**Comment by dustenhubbard** [comment]
Can confirm that this solution works, thank you!
